base:
     project: 'wine app teju'
     random_state: 42
     Target_col: TARGET

data_source:
           s3_source: data_given/winequality.csv

load_data:
         raw_dataset_csv: data/raw/winequality.csv

split_data:
          train_path: data/processed/train_winequality.csv
          test_path: data/processed/test_winequlaity.csv
          test_split: 0.2

estimators:
          ElasticNet:
              params:
                  alpha: 0.88
                  l1_ratio: 0.89

model_dir: saved_models